name: github pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Install prereqs
        run: sudo apt-get install -y plantuml graphviz

      - uses: actions-rs/install@v0.1
        with:
          crate: mdbook-admonish
          version: latest
      - uses: actions-rs/install@v0.1
        with:
          create: mdbook-ktex
          version: latest
      - uses: actions-rs/install@v0.1
        with:
          create: graphviz
          version: latest
      - uses: actions-rs/install@v0.1
        with:
          create: mdbook-mermaid
          version: latest
      - uses: actions-rs/install@v0.1
        with:
          create: mdbook-plantuml
          version: latest

      - uses: cachix/install-nix-action@v18
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.21'

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
